name: Code Coverage Check

on: [push, pull_request]

jobs:
  coverage-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run coverage report
        run: |
          coverage run --omit 'oplog/tests/*','*/__pycache__/*' -m pytest
          coverage report -m --fail-under=90

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage.xml

      - name: Fail if coverage is below threshold
        run: |
          if [ -f coverage.xml ]; then
            python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); lines = root.find('totals').find('lines').get('percent'); exit(1) if float(lines) < X else exit(0);" || true
          fi
