name: Code Coverage Check

on: [pull_request]

env:
  COVERAGE_THRESHOLD: 95

jobs:
  coverage-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run coverage report
        run: |
          coverage run --omit 'oplog/tests/*','*/__pycache__/*' -m pytest
          coverage xml -o coverage.xml
          coverage report -m --fail-under=$COVERAGE_THRESHOLD

      - name: Upload coverage report
        if: success()  # Only upload the report if previous steps were successful
        run: |
          if [ -f coverage.xml ]; then
            echo "Uploading coverage report"
          else
            echo "Coverage report not found, failing the workflow"
            exit 1
          fi
        shell: bash

      - name: Fail if coverage is below threshold
        run: |
          if [ -f coverage.xml ]; then
            python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); lines = root.find('totals').find('lines').get('percent'); exit(1) if float(lines) < $COVERAGE_THRESHOLD else exit(0);" || true
          else
            echo "Coverage report not found, failing the workflow"
            exit 1
          fi
        shell: bash
