name: Security Check

on: [push, pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest
    name: PyCharm Python Security Scanner
    steps:
        - uses: actions/checkout@v3
        - uses: tonybaloney/pycharm-security@1.25.1

                